To Do List - Add and edit/remove functionality
hajnaloltyan/to-do-list-vjs pull request #2
Opened 2023-05-04 21:56 UTC by hajnaloltyan

To Do List - Day 2: Add and edit/remove

* Update icons into buttons
* Create new JS file to have functionality: 
               - Add task
               - Edit task's name
               - Remove task
* Saving all to localstorage
* Keep task index updated when other task is removed

* [Live Demo](https://hajnaloltyan.github.io/to-do-list-vjs/)

*Site was deployed by adding scripts to use gh-pages*

2023-05-04 23:03 UTC, FrederickMih requested changes
## Hi :raising_hand:  @hajnaloltyan, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



<img src="https://media.giphy.com/media/nYYtQdLqwwlTe3ccKh/giphy.gif"  width ="150"><img>

## Highlights :green_circle: 

- PR is professional :+1: 
- Descriptive README.md file :+1: 
- Changes to the Todo List are saved in local storage :+1:  


## Required Changes ♻️
**N/A**
_Check the comments under the review._

## Optional suggestions
**N/A**
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 23:03 UTC, FrederickMih commented on src/createTask.js
> +
- [ ] We are supposed to implement a function for editing task descriptions. Right now, when I try to edit a task, the index of the task replaces the task of the first index when reload as you can see in the short video demo below:


[Screencast from 05-04-2023 11:38:30 PM.webm](https://user-images.githubusercontent.com/63087491/236347614-2467034a-26c9-48cb-9e5a-9cbc58dfbf76.webm)

- Please fix the issue

2023-05-05 12:40 UTC, NahnahAJ requested changes
## Project Status: CHANGES REQUIRED :recycle: 
Hi @hajnaloltyan , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which haven't been addressed yet.
<img src="https://media2.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/>

 ## Highlights
- Most requested changes implemented :heavy_check_mark: 
- No linter errors :heavy_check_mark: 
- Professional Pull Request :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 12:40 UTC, NahnahAJ commented on src/createTask.js
> +        }
- [ ] Great job fixing the bug the previous reviewer talked about. I see that it's working fine now. However, I noticed that the updated changes aren't getting saved into the local storage, and as a result, when the page is refreshed, the text changes to what it was originally. So kindly fix this as well :100: 
- Video Reference 

[Screencast from 05-05-2023 12:27:45 PM.webm](https://user-images.githubusercontent.com/102699958/236459675-208633e7-e939-4f56-b030-259efae726ac.webm)

2023-05-05 15:36 UTC, medaminedev66 commented
Hello @hajnaloltyan 👋,

_This is an additional review as a result of the second opinion request._

I can confirm that the user can edit the task after clicking on the three points icon and then the save icon. The user experience was hard to examined. That's why we encourage you to write a descriptive summary about the changes you worked on so that the code reviewer knows about it.

Anyway, there are some issues with the user experience that need to be addressed. Currently, when a user wants to remove a task, they need to save it first before the remove icon is displayed. However, even after clicking on the remove icon, the task is not deleted from the local storage. We need to fix this issue.

Moreover, users are not able save a new edit of the task after the first edit. This limitation makes the app less user-friendly. To enhance the user experience, we should allow users to edit their tasks at any time. This improvement will make the app more efficient and convenient for users.

Keep rocking 🚀!

2023-05-05 19:47 UTC, Trast00 approved these changes
# Approved 🟢
Hi @hajnaloltyan , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![allfather-approves-approved](https://user-images.githubusercontent.com/74411135/225065704-3948f35e-94b9-4440-a31a-29bba50b3c4d.gif)

## Highlights
- Project look awsome 🍏 🌷 
- Code is clean and well organized 🧼 💯 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [ ] **[OPTIONAL]**Kindly, consider adding some element in the **future feature** section of the README.md file. Document your readme file will make your project look much more professional 😊 and help you show a great documentation skill 😄

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@Trast00) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 20:32 UTC, merged